language: bash
services: docker
install:
    - docker build -t moodle-php-fpm .
script:
    - "docker run --name test0 -d -p 8000:80 -v $PWD/tests/fixtures:/var/www/html moodle-php-fpm"
    - docker exec test0 php /var/www/html/test.php
    #- curl --fail http://127.0.0.1:8000/test.php
after_failure:
    - docker logs test0
after_script:
    - docker rm -f test0
